# Generated by Django 4.1 on 2024-04-10 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=32, unique=True)),
                ('department_desc', models.TextField(blank=True)),
                ('department_slug', models.SlugField(blank=True, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_category', models.CharField(max_length=32, unique=True)),
                ('deposit_desc', models.TextField(blank=True)),
                ('deposit_value', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Deposit Information',
            },
        ),
        migrations.CreateModel(
            name='tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_category', models.CharField(max_length=32, unique=True)),
                ('tax_desc', models.TextField(blank=True)),
                ('tax_percentage', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name_plural': 'Tax Information',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=125)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('qty', models.IntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.department')),
                ('deposit_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.deposit')),
                ('tax_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.tax')),
            ],
        ),
    ]
